import type { Metadata } from "next";
import "./globals.css";
import { Martian_Mono } from 'next/font/google';

const martianMono = Martian_Mono({
  weight: ["100", "200", "300", "400", "500"],
  variable: "--font-martian-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hack CWRU 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={martianMono.variable}
      >
        {children}
      </body>
    </html>
  );
}
